---
version: "3.8"
services:
  prd-vpn-server-app:
    image: docker-registry.theautomation.nl/coen/prd-vpn-server-app:latest
    container_name: prd-vpn-server-app
    restart: unless-stopped
    env_file: prd-vpn-server-app.env
    networks:
      - vpn-server
    ports:
      - "500:500/udp"
      - "4500:4500/udp"
    privileged: true

# NETWORKS
networks:
  vpn-server:
    driver: bridge
    name: vpn-server
    ipam:
      config:
        - subnet: 172.30.0.0/16
