---
version: "3.8"
services:
  prd-vpn-server-app:
    image: docker-registry.theautomation.nl/coen/prd-vpn-server-app:latest
    container_name: prd-vpn-server-app
    restart: unless-stopped
    env_file: prd-vpn-server-app.env
    networks:
      - vpn-server
      - reverse-proxy
    ports:
      - 500:500/udp
      - 4500:4500/udp
    privileged: true

networks:
  reverse-proxy:
    name: reverse-proxy
  vpn-server:
    driver: bridge
    name: vpn-server
    ipam:
      config:
        - subnet: 172.37.0.0/16
